enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
build-mode = "both"
apkmirror-dpi = "120-640dpi"
arch = "all"