enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

[SonySoundConnect]
apkmirror-dlurl = "https://www.apkmirror.com/apk/sony-corporation/sony-headphones-connect"
uptodown-dlurl = "https://sony-headphones-connect.en.uptodown.com/android"
build-mode = "both"
arch = "arm64-v8a + armeabi-v7a"
apkmirror-dpi = "120-640dpi"