enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

[SolidExplorer]
apkmirror-dlurl = "https://www.apkmirror.com/apk/neatbytes/solid-explorer-beta"
uptodown-dlurl = "https://solid-explorer-file-manager.en.uptodown.com/android"
build-mode = "both"
arch = "all"
