enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

[Spotify]
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
build-mode = "both"
arch = "both"