enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

[Yuka]
apkmirror-dlurl = "https://www.apkmirror.com/apk/yuka-apps/yuka-food-cosmetic-scan"
uptodown-dlurl = "https://yuka.en.uptodown.com/android"
build-mode = "both"
arch = "all"