enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

[GoogleNews]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/google-news"
uptodown-dlurl = "https://google-play-newsstand.en.uptodown.com/android"
build-mode = "both"
arch = "all"
