enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

[GoogleRecorder]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/google-recorder"
uptodown-dlurl = "https://opnemer.en.uptodown.com/android"
build-mode = "both"
apkmirror-dpi = "120-640dpi"
arch = "both"