enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

[Messenger]
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger"
uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"
build-mode = "both"
arch = "both"
version = "auto"
