enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
build-mode = "both"

[Messenger]
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger/"
build-mode = "both"

[YouTubeMusic]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
build-mode = "both"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
build-mode = "both"

[Tiktok]
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
build-mode = "both"

[Twitch]
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch/"
build-mode = "both"

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
build-mode = "both"
included-patches = "'Open links with app chooser'"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "both"

[Amazon]
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-shopping/"
build-mode = "both"

[Backdrops]
apkmirror-dlurl = "https://www.apkmirror.com/apk/backdrops/backdrops-wallpapers/"
build-mode = "both"

[Bandcamp]
apkmirror-dlurl = "https://www.apkmirror.com/apk/bandcamp-inc/bandcamp/"
build-mode = "both"

[Duolingo]
apkmirror-dlurl = "https://www.apkmirror.com/apk/duolingo/duolingo-duolingo/"
build-mode = "both"
included-patches = "'Disable ads'"
exclusive-patches = true

[Facebook]
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook/"
build-mode = "both"

[GoogleNews]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/google-news/"
build-mode = "both"

[GooglePhotos]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
build-mode = "both"

[GoogleRecorder]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/google-recorder/"
build-mode = "both"

[IconPackStudio]
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"
build-mode = "both"

[Lightroom]
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom/"
build-mode = "both"

[MemeGenerator]
apkmirror-dlurl = "https://www.apkmirror.com/apk/zombodroid/meme-generator-free/"
build-mode = "both"

[MyFitnessPal]
apkmirror-dlurl = "https://www.apkmirror.com/apk/myfitnesspal-inc/calorie-counter-myfitnesspal/"
build-mode = "both"

[NetGuard]
apkmirror-dlurl = "https://www.apkmirror.com/apk/marcel-bokhorst/netguard-no-root-firewall/"
build-mode = "both"

[Photomath]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photomath/"
build-mode = "both"

[pixiv]
apkmirror-dlurl = "https://www.apkmirror.com/apk/pixiv-inc/pixiv/"
build-mode = "both"

[RAR]
apkmirror-dlurl = "https://www.apkmirror.com/apk/rarlab-published-by-win-rar-gmbh/rar/"
build-mode = "both"

[SolidExplorer]
apkmirror-dlurl = "https://www.apkmirror.com/apk/neatbytes/solid-explorer-beta/"
build-mode = "both"

[SonySoundConnect]
apkmirror-dlurl = "https://www.apkmirror.com/apk/sony-corporation/sony-headphones-connect/"
build-mode = "both"

[SoundCloud]
apkmirror-dlurl = "https://www.apkmirror.com/apk/soundcloud/soundcloud-soundcloud/"
build-mode = "both"

[Stocard]
apkmirror-dlurl = "https://www.apkmirror.com/apk/stocard-gmbh/stocard-rewards-cards-wallet/"
build-mode = "both"

[Strava]
apkmirror-dlurl = "https://www.apkmirror.com/apk/strava-inc/strava-run-bike-hike-3/"
build-mode = "both"

[TickTick]
apkmirror-dlurl = "https://www.apkmirror.com/apk/ticktick-limited/ticktick-to-do-list-with-reminder-day-planner/"
build-mode = "both"

[trakt.TV]
apkmirror-dlurl = "https://www.apkmirror.com/apk/trakt/trakt/"
build-mode = "both"

[Tumblr]
apkmirror-dlurl = "https://www.apkmirror.com/apk/tumblr-inc/tumblr/"
build-mode = "both"

[Yuka]
apkmirror-dlurl = "https://www.apkmirror.com/apk/yuka-apps/yuka-food-cosmetic-scan/"
build-mode = "both"
