enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

[trakt]
apkmirror-dlurl = "https://www.apkmirror.com/apk/trakt/trakt"
uptodown-dlurl = "https://trakt.en.uptodown.com/android"
build-mode = "both"
apkmirror-dpi = "160-640dpi"