enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

[Strava]
apkmirror-dlurl = "https://www.apkmirror.com/apk/strava-inc/strava-run-bike-hike-3"
uptodown-dlurl = "https://strava.en.uptodown.com/android"
build-mode = "both"
apkmirror-dpi = "120-640dpi"