enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"
build-mode = "both"
included-patches = "'Open links with app chooser'"
apkmirror-dpi = "120-640dpi"
arch = "all"
